### ISSUE TITLE
Face detection code is not working on android.

### ISSUE THREAD

**Issue by wsoftone** [georg-jung/FaceAiSharp#41] opened 2024-04-15 16:40 UTC
Hi Georg--jung, i tried to implement an example to detect and recognise faces in .Net Maui. I am able to make it work on win device but not on android device. I am getting this exception on android:  
**Microsoft.ML.OnnxRuntime.OnnxRuntimeException: '[ErrorCode:NoSuchFile] Load model from /data/data/com.companyname.faceaitestmaui/files/.__override__/onnx/scrfd_2.5g_kps.onnx failed:Load model /data/data/com.companyname.faceaitestmaui/files/.__override__/onnx/scrfd_2.5g_kps.onnx failed. File doesn't exist'**

Does your plugin works on android or it is designed to work on windows only?

best regards.

**Comment by georg-jung** [comment] 2024-04-30 12:58
Duplicate of #37, see my response there :)

**Closed by georg-jung** 2024-04-30 12:58 UTC
